- name: verify if docker-compose is installed
  stat: path=/usr/bin/docker-compose
  register: docker_compose_installed

- name: install docker compose
  include_tasks: install-docker-compose.yml
  when: not docker_compose_installed.stat.exists
